<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>72161f33-32c2-4fc1-a039-81b3822f4ac8</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Mapster" Version="10.0.7" />
        <PackageReference Include="Mapster.DependencyInjection" Version="10.0.7" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0"/>
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.1.7" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\TaskFlow.Application\TaskFlow.Application.csproj" />
      <ProjectReference Include="..\TaskFlow.Infrastructure\TaskFlow.Infrastructure.csproj" />
    </ItemGroup>

</Project>
